spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/MoonVs}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

api:
  security:
    token:
      secret: ${JWT_SECRET:secret-key}

logging:
  level:
    org.springframework.security: DEBUG