spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/MoonVs?stringtype=unspecified}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

front:
  url: ${FRONT_URL}

api:
  security:
    token:
      secret: ${JWT_SECRET:secret-key}

tmdb:
  url: https://api.themoviedb.org/3/%s%s
  token: ${TMDB_TOKEN}

logging:
  level:
    org.springframework.security: DEBUG